version: '3.8'
services:

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=yrro
      - POSTGRES_PASSWORD=yrro
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
